### ISSUE TITLE
Build for OSX failed

### ISSUE THREAD

**Issue by iazarov** [OData/odatacpp-client#24]
Step 4 for OSX build is to build the dependency library Casablanca v2.1.0.
This step failed with the error:

>../odatacpp-client/lib/casablanca/Release/libs/websocketpp/websocketpp/common/network.hpp:53:17: error: expected ')'
inline uint64_t htonll(uint64_t src) {
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/sys/_endian.h:141:25: note: expanded
      from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libkern/_OSByteOrder.h:78:30: note: 
      expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))

I tried to use v2.3.0 that successfully was build with MacOSX10.10, however, it causes the error on step 5 while building odatacpp_client.

Is odatacpp_client compatible with MacOSX10.10?
Is it possible to get the binaries for IOS?

**Comment by iazarov** [comment]
after removing htonll() functions from ../casablanca/Release/libs/websocketpp/websocketpp/common/network.hpp
and fixing calls to the function the build was OK
